/**
 * DOCX export — the document-building logic runs for real; only the browser
 * download boundary (`URL.createObjectURL`) is stubbed so the generated .docx
 * bytes can be unzipped and inspected. Selection ids are deliberately NOT
 * uuids, so `fetchEnrichedData` short-circuits before touching Supabase.
 */
import { TextEncoder, TextDecoder } from 'util';
import { Blob as NodeBlob } from 'buffer';
// jsdom (jest 30) doesn't provide TextEncoder, and its Blob has no working
// arrayBuffer(); `docx`'s packer needs the former and the test reads the
// generated bytes back through the latter.
Object.assign(globalThis, { TextEncoder, TextDecoder, Blob: NodeBlob });

const NOTE_SEL_ID = '11111111-1111-4111-8111-111111111111';
let mockNoteContent = '';
jest.mock('../supabase/client', () => ({
  createClient: () => ({
    from: (table: string) => ({
      select: () => ({
        in: async () =>
          table === 'notes'
            ? { data: [{ selection_id: NOTE_SEL_ID, content: mockNoteContent }] }
            : { data: [] },
      }),
    }),
  }),
}));

import JSZip from 'jszip';
import { exportAsDocx, exportAsMarkdown, type TagRow } from '../tagExport';

let capturedBlob: Blob | null = null;

beforeAll(() => {
  // jsdom implements neither of these.
  (URL as unknown as { createObjectURL: (b: Blob) => string }).createObjectURL = (b: Blob) => {
    capturedBlob = b;
    return 'blob:mock';
  };
  (URL as unknown as { revokeObjectURL: (u: string) => void }).revokeObjectURL = () => {};
});

beforeEach(() => {
  capturedBlob = null;
});

function tagAtDepth(i: number, depth: number): TagRow {
  return {
    id: `t${i}`,
    name: `Level ${depth}`,
    parent_id: i === 0 ? null : `t${i - 1}`,
    depth,
    sort_order: 0,
    created_at: new Date().toISOString(),
    visibility: 'private',
    selections: [
      {
        id: `s${i}`, // not a uuid → no Supabase call
        snapshot_text: 'quote text',
        passage_id: 'p1',
        book_id: 'b',
        book_title: 'B',
        citation: '— X.',
      },
    ],
  };
}

async function docXmlOf(tags: TagRow[]): Promise<string> {
  await exportAsDocx(tags, { includeNotes: false, includeXrefs: false });
  expect(capturedBlob).not.toBeNull();
  const buf = Buffer.from(await capturedBlob!.arrayBuffer());
  const zip = await JSZip.loadAsync(buf);
  return zip.file('word/document.xml')!.async('string');
}

describe('exportAsMarkdown — note line breaks', () => {
  function tagWithNoteSel(): TagRow {
    return {
      id: 't0', name: 'Test Compilation', parent_id: null, depth: 0, sort_order: 0,
      created_at: new Date().toISOString(), visibility: 'private',
      selections: [{
        id: NOTE_SEL_ID, snapshot_text: 'quote text', passage_id: 'p1',
        book_id: 'b', book_title: 'B', citation: '— X.',
      }],
    };
  }

  async function mdOf(tags: TagRow[]): Promise<string> {
    await exportAsMarkdown(tags, { includeNotes: true, includeXrefs: false });
    expect(capturedBlob).not.toBeNull();
    return capturedBlob!.text();
  }

  it('renders a hard-enter inside a note as a Markdown hard break, not a dropped one', async () => {
    mockNoteContent = 'First line of the note.\nSecond line of the note.';
    const md = await mdOf([tagWithNoteSel()]);
    expect(md).toContain('- First line of the note.  \n  Second line of the note.');
  });

  it('leaves a single-line note untouched', async () => {
    mockNoteContent = 'Just one line.';
    const md = await mdOf([tagWithNoteSel()]);
    expect(md).toContain('- Just one line.');
    expect(md).not.toContain('Just one line.  \n');
  });
});

describe('exportAsDocx — Word heading outline levels', () => {
  it('gives each depth its matching Heading style, clamped at Heading6', async () => {
    const xml = await docXmlOf([0, 1, 2, 3, 4, 5, 6].map((d, i) => tagAtDepth(i, d)));
    const styles = [...xml.matchAll(/<w:pStyle w:val="(Heading\d)"\/>/g)].map(m => m[1]);
    expect(styles).toEqual(['Heading1', 'Heading2', 'Heading3', 'Heading4', 'Heading5', 'Heading6', 'Heading6']);
  });

  it('does not put a heading style on quote / citation paragraphs', async () => {
    const xml = await docXmlOf([tagAtDepth(0, 0)]);
    expect([...xml.matchAll(/<w:pStyle w:val="Heading\d"\/>/g)]).toHaveLength(1);
  });
});
